## REST-Client script
# If you don't know how to use this script, see: https://github.com/pashky/restclient.el for instruction

#
# should echo
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{"jsonrpc": "2.0", "method": "echo", "params": "plutus-apps rocks", "id": 0}
#
# should fail. `add` method is unknown
POST http://localhost:3000/json-rpc
Content-Type: application/json
{"jsonrpc": "2.0", "method": "add", "params": [1,1], "id": 0}
#
# should fail, Unknown method: unknownMethod
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "unknownMethod"
, "params": "addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0"
, "id": 2
}
#
# lookup for UTXOs , should return result lots of data
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": "addr_test1vpfwv0ezc5g8a4mkku8hhy3y3vp92t7s3ul8g778g5yegsgalc6gc"
, "id": 92
}
#
# lookup for UTXOs, should generate error if the address is not in the target list
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": "addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj"
, "id":21
}

#
# lookup for UTXOs, should generate error if the address is not in the target list
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": ["addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj"]
, "id":21
}


#
# addresses with non null dautm
#
# "addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk"
# addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
# addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0
#
# WHERE datum  IS NOT NULL AND inLineScript IS NOT NULL
#
#addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk
#addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
#addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0

#
# it should fail, "Error in $: expected String, but encountered Number"
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": 100
, "id": 14
}
#
# fetch plutus converted addresses the user had provided
# This version of marconi-sidechain simply ignores `100` and returns all rows from database. This is a todo item for next release
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getTargetAddresses"
, "params": ""
, "id": 11
}
#
#
####  REST calls ####
#
# REST call, get the current time.  This may be used as health-check
GET http://localhost:3000/rest/time
#
# REST call, get the user-provided addresses
GET http://localhost:3000/rest/addresses
