## REST-Client script
# If you don't know how to use this script, see: https://github.com/pashky/restclient.el for instruction

#
# should echo
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{"jsonrpc": "2.0", "method": "echo", "params": "plutus-apps rocks", "id": 0}
#
# should return targetAddresses, if any
POST http://localhost:3000/json-rpc
Content-Type: application/json
{"jsonrpc": "2.0", "method": "getTargetAddresses", "params": "hello", "id": 1}
#
# should fail, Unknown method: unknownMethod
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "unknownMethod"
, "params": "addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0"
, "id": 2
}
#
# lookup for UTXOs , should return result lots of data
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params":
    { "address": "addr_test1wpzewuy339m9l8ax7gz8g08q2j9478lgntzv9qhmwvy3hwg0cwsaf"
    }
, "id": 3
}
#
# lookup for UTXOs up to a given slot, should return result lots of data
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params":
    { "address": "addr_test1wpzewuy339m9l8ax7gz8g08q2j9478lgntzv9qhmwvy3hwg0cwsaf"
    , "slotNo": 10000
    }
, "id": 3
}
#
# lookup for UTXOs, should generate error if the address is not in the target list
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": "addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj"
, "id":4
}


#
# addresses with non null dautm
#
# "addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk"
# addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
# addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0
#
# WHERE datum  IS NOT NULL AND inLineScript IS NOT NULL
#
#addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk
#addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
#addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0

#
# it should fail, "Error in $: expected String, but encountered Number"
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "getUtxoFromAddress"
, "params": 100
, "id": 5
}
#
#
#
####  REST calls ####
#
# REST call, get the current time.  This may be used as health-check
GET http://localhost:3000/rest/time
#
# REST call, get the user-provided addresses
GET http://localhost:3000/rest/addresses
