
version: 2

sphinx:
  configuration: doc/conf.py

formats:
  - pdf
  - epub

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: doc/requirements.txt
