version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    # This means "latest version 3", which seems fine
    python: "3"

python:
  install:
    - requirements: doc/requirements.txt