name:                hysterical-screams
version:             0.1.0.0
github:              "githubuser/hysterical-screams"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"
category:            "Testing"
synopsis:            "Exercises in Algebra Driven Design"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hysterical-screams#readme>

default-extensions:
  - ImportQualifiedPost
  - ExplicitForAll
  - ScopedTypeVariables
  - TypeApplications
  - PatternSynonyms
  - DeriveGeneric
  - NamedFieldPuns
  - MultiParamTypeClasses
  - FlexibleInstances
  - OverloadedStrings
  - GADTs

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- quickspec
- sqlite-simple

library:
  source-dirs: src
  ghc-options:
  - -Wall

verbatim:
  Tested-With: GHC ==8.10.7

tests:
  hysterical-screams-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hysterical-screams
    - QuickCheck
    - quickspec
    - tasty
    - tasty-quickcheck
    - containers
