# FIXME: stack cannot build `plutus-ledger` with the dependency on `cardano-api:gen`.
# As it doesn't support public sublibraries yet.
# https://github.com/commercialhaskell/stack/issues/5318.
# Making it only being able to build ~98% of this repository.

resolver: lts-18.13

packages:
- doc
- freer-extras
- playground-common
- plutus-chain-index
- plutus-contract
- plutus-ledger
- plutus-pab
- plutus-playground-server
- plutus-use-cases
- quickcheck-dynamic
- web-ghc

extra-deps:
- OddWord-1.0.2.0@sha256:5d848ff5db2c0457ce37ccc8898ce2b6b880a1c6a78e5b16841328a7404ff5ee,1888
- Unique-0.4.7.9@sha256:a7e154cf6d05169777a1e54aadab24fb3a6eae3ee167e5e77d7ba96d182436c7,2064
- async-timer-0.2.0.0@sha256:e1504aa0fb5932cb07498ec548180aba9e03a3e7f5d2c810bf3dce75fbdd34d6,2048
- beam-core-0.9.1.0@sha256:70659e3046bfecda49b1b921bf088899bad859ea649552c78d464e634740b107,5282
- beam-migrate-0.5.1.0@sha256:55d5fae17584c14b654d19d9de01f0a65e6c229561ce4fd12de92eba98b39105,4923
- beam-sqlite-0.5.1.0@sha256:ec2a5cf9cc427a57c1c6872194450cd2e5d287e7a50b1ab554badb5138e78e7d,3634
- canonical-json-0.6.0.0@sha256:9021f435ccb884a3b4c55bcc6b50eb19d5fc3cc3f29d5fcbdef016f5bbae23a2,3488
- composition-prelude-3.0.0.2@sha256:1ffed216bd28d810fce0b5be83a661e2a892696d73b3f8de5c0f5edb9b5f0090,1216
- dom-lt-0.2.2.1@sha256:6b005b64f10a0f73f716898e0f4b4d93a02c31dc8abb155c14afd870e3abf9ac,1778
- gray-code-0.3.1@sha256:2c8a4ed9c9ee37320305610604d6d93504e0813d7c9768949af418b53043185a,2388
- lazy-search-0.1.2.1@sha256:c942a01e4a64881f89c72eaef5e3a78eba8750759cd66996c6746a2a7cabe703,1199
- libsystemd-journal-1.4.5@sha256:dc68296f5d874b48ba187dbd0af4de8182ba57cb6ebaa46c05ac61c1b3c6c396,1238
- monoidal-containers-0.6.0.1@sha256:f56ea8fe91ff93da140e38b8dab4b94437b901818c13ba72fc7fc802290323ee,2583
- moo-1.2@sha256:0c4be1a01548db785dcbbe6b8c98579dbf03c5b3b536e0420dce3ba6a61337cb,5951
- nothunks-0.1.3@sha256:33bb3af223163535fa59d1fa83ba95a355106ba3fcffe5452d4abbf13ab4608d,2521
- partial-order-0.2.0.0@sha256:a0d6ddc9ebcfa965a5cbcff1d06d46a79d44ea5a0335c583c2a51bcb41334487,2275
- row-types-1.0.1.2@sha256:5c56e91d30b61f275eaee0d97b015d5332d95d7599e57582d6e62a43aa388087,2948
- servant-options-0.1.0.0@sha256:39f50166a68006250e79370372f553ca476f14d06d93fa0c401050253aeba803,914
- servant-subscriber-0.7.0.0@sha256:e54a3ca6d52227025081bbc470a3af35efecbe0f82050d06aa5c9bbdf05795a6,2635
- servant-websockets-2.0.0@sha256:6e9e3600bced90fd52ed3d1bf632205cb21479075b20d6637153cc4567000234,2253
- size-based-0.1.2.0@sha256:1b33da89d270189661dbbda49a88b0c21d2fc2f7a407e7a2b1933e2faf0f5d4d,1258
- statistics-linreg-0.3@sha256:95c6efe6c7f6b26bc6e9ada90ab2d18216371cf59a6ef2b517b4a6fd35d9a76f,2544
- streaming-binary-0.2.2.0@sha256:09b9a9b0291199c5808e88dcf9c93e7b336e740c71efeafd7c835b59794a8c90,1034
- time-interval-0.1.1@sha256:7bfd3601853d1af7caa18248ec10b01701d035ac274a93bb4670fea52a14d4e8,2567
- time-out-0.2@sha256:b9a6b4dee64f030ecb2a25dca0faff39b3cb3b5fefbb8af3cdec4142bfd291f2,3010
- transformers-except-0.1.2@sha256:2ff895fd65ec9e45cbe839ef5b66e26b7d9f3fe561148993293a41e14491e625,1548

# Outside of Stackage LTS
- hspec-2.8.3      # For `cardano-wallet`
- hspec-core-2.8.3 # For `cardano-wallet`
- network-3.1.2.5  # For `network-mux`

# cabal.project is the source of truth for these pins, they are explained there
# and need to be kept in sync.
- git: https://github.com/Quid2/flat.git
  commit: ee59880f47ab835dbd73bea0847dab7869fc20d8
- git: https://github.com/input-output-hk/purescript-bridge.git
  commit: 366fc70b341e2633f3ad0158a577d52e1cd2b138
- git: https://github.com/input-output-hk/servant-purescript.git
  commit: ebea59c7bdfc0338d83fca772b9a57e28560bcde
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: 07397f0e50da97eaa0575d93bee7ac4b2b2576ec
- git: https://github.com/input-output-hk/cardano-config
  commit: e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
- git: https://github.com/input-output-hk/cardano-base
  commit: 41545ba3ac6b3095966316a99883d678b5ab8da8
  subdirs:
    - base-deriving-via
    - binary
    - binary/test
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-tests
    - measures
    - orphans-deriving-via
    - slotting
    - strict-containers
- git: https://github.com/input-output-hk/cardano-prelude
  commit: fd773f7a58412131512b9f694ab95653ac430852
  subdirs:
    - cardano-prelude
    - cardano-prelude-test
- git: https://github.com/input-output-hk/cardano-addresses
  commit: d2f86caa085402a953920c6714a0de6a50b655ec
  subdirs:
    - core
- git: https://github.com/input-output-hk/cardano-wallet
  commit: 25ef435c6e6a30d9d8ce3e454ee20845bdc4ae10
  subdirs:
    - lib/dbvar
    - lib/text-class
    - lib/strict-non-empty-containers
    - lib/core
    - lib/test-utils
    - lib/numeric
    - lib/launcher
    - lib/core-integration
    - lib/cli
    - lib/shelley
- git: https://github.com/input-output-hk/ouroboros-network
  commit: d2d219a86cda42787325bb8c20539a75c2667132
  subdirs:
    - io-sim
    - io-classes
    - monoidal-synchronisation
    - network-mux
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - ouroboros-network-testing
    - strict-stm
    - typed-protocols
    - typed-protocols-cborg
    - typed-protocols-examples
    - ntp-client
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 46f994e216a1f8b36fe4669b47b2a7011b0e153c
  subdirs:
    - iohk-monitoring
    - tracer-transformers
    - contra-tracer
    - plugins/backend-aggregation
    - plugins/backend-ekg
    - plugins/backend-monitoring
    - plugins/backend-trace-forwarder
    - plugins/scribe-systemd
- git: https://github.com/input-output-hk/cardano-ledger
  commit: 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5
  subdirs:
    eras/alonzo/impl
    eras/alonzo/test-suite
    eras/byron/chain/executable-spec
    eras/byron/ledger/executable-spec
    eras/byron/ledger/impl
    eras/byron/ledger/impl/test
    eras/byron/crypto
    eras/byron/crypto/test
    eras/shelley/impl
    eras/shelley/test-suite
    eras/shelley-ma/impl
    eras/shelley-ma/test-suite
    libs/cardano-ledger-core
    libs/cardano-ledger-example-shelley
    libs/cardano-ledger-pretty
    libs/cardano-ledger-test
    libs/cardano-protocol-tpraos
    libs/plutus-preprocessor
    libs/ledger-state
    libs/non-integral
    libs/small-steps
    libs/small-steps-test
    libs/cardano-data
    libs/set-algebra
    libs/compact-map
- git: https://github.com/input-output-hk/cardano-node.git
  commit: 814df2c146f5d56f8c35a681fe75e85b905aed5d
  subdirs:
    - cardano-api
    - cardano-cli
    - cardano-node
    - cardano-node-chairman
  # Using a fork until our patches can be merged upstream
- git: https://github.com/input-output-hk/optparse-applicative
  commit: 7497a29cb998721a9068d5725d49461f2bba0e7a
- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d
- git: https://github.com/input-output-hk/goblins
  commit: cde90a2b27f79187ca8310b6549331e59595e7ba
- git: https://github.com/input-output-hk/plutus
  commit: 3f089ccf0ca746b399c99afe51e063b0640af547
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - word-array
    - prettyprinter-configurable
    - stubs/plutus-ghc-stub

allow-newer: true
