(program
  (let
    (nonrec)
    (datatypebind
      (datatype
        (tyvardecl Monoid (fun (type) (type)))
        (tyvardecl a (type))
        Monoid_match
        (vardecl
          CConsMonoid
          (fun [ (lam a (type) (fun a (fun a a))) a ] (fun a [ Monoid a ]))
        )
      )
    )
    (termbind
      (strict)
      (vardecl
        p1Monoid
        (all a (type) (fun [ Monoid a ] [ (lam a (type) (fun a (fun a a))) a ]))
      )
      (abs
        a
        (type)
        (lam
          v
          [ Monoid a ]
          [
            { [ { Monoid_match a } v ] [ (lam a (type) (fun a (fun a a))) a ] }
            (lam v [ (lam a (type) (fun a (fun a a))) a ] (lam v a v))
          ]
        )
      )
    )
    (termbind
      (strict)
      (vardecl mempty (all a (type) (fun [ Monoid a ] a)))
      (abs
        a
        (type)
        (lam
          v
          [ Monoid a ]
          [
            { [ { Monoid_match a } v ] a }
            (lam v [ (lam a (type) (fun a (fun a a))) a ] (lam v a v))
          ]
        )
      )
    )
    (let
      (rec)
      (datatypebind
        (datatype
          (tyvardecl List (fun (type) (type)))
          (tyvardecl a (type))
          Nil_match
          (vardecl Nil [ List a ])
          (vardecl Cons (fun a (fun [ List a ] [ List a ])))
        )
      )
      (let
        (rec)
        (termbind
          (strict)
          (vardecl
            fFoldableNil_cfoldMap
            (all
              m
              (type)
              (all
                a (type) (fun [ Monoid m ] (fun (fun a m) (fun [ List a ] m)))
              )
            )
          )
          (abs
            m
            (type)
            (abs
              a
              (type)
              (lam
                dMonoid
                [ Monoid m ]
                (lam
                  ds
                  (fun a m)
                  (lam
                    ds
                    [ List a ]
                    {
                      [
                        [
                          { [ { Nil_match a } ds ] (all dead (type) m) }
                          (abs dead (type) [ { mempty m } dMonoid ])
                        ]
                        (lam
                          x
                          a
                          (lam
                            xs
                            [ List a ]
                            (abs
                              dead
                              (type)
                              [
                                [ [ { p1Monoid m } dMonoid ] [ ds x ] ]
                                [
                                  [
                                    [
                                      { { fFoldableNil_cfoldMap m } a } dMonoid
                                    ]
                                    ds
                                  ]
                                  xs
                                ]
                              ]
                            )
                          )
                        )
                      ]
                      (all dead (type) dead)
                    }
                  )
                )
              )
            )
          )
        )
        (let
          (rec)
          (termbind
            (strict)
            (vardecl
              foldr
              (all
                a
                (type)
                (all
                  b (type) (fun (fun a (fun b b)) (fun b (fun [ List a ] b)))
                )
              )
            )
            (abs
              a
              (type)
              (abs
                b
                (type)
                (lam
                  f
                  (fun a (fun b b))
                  (lam
                    acc
                    b
                    (lam
                      l
                      [ List a ]
                      {
                        [
                          [
                            { [ { Nil_match a } l ] (all dead (type) b) }
                            (abs dead (type) acc)
                          ]
                          (lam
                            x
                            a
                            (lam
                              xs
                              [ List a ]
                              (abs
                                dead
                                (type)
                                [
                                  [ f x ] [ [ [ { { foldr a } b } f ] acc ] xs ]
                                ]
                              )
                            )
                          )
                        ]
                        (all dead (type) dead)
                      }
                    )
                  )
                )
              )
            )
          )
          (let
            (nonrec)
            (typebind (tyvardecl Unit (type)) (all a (type) (fun a a)))
            (datatypebind
              (datatype
                (tyvardecl MultiSig (type))

                MultiSig_match
                (vardecl
                  MultiSig
                  (fun [ List (con bytestring) ] (fun (con integer) MultiSig))
                )
              )
            )
            (typebind (tyvardecl ScriptPurpose (type)) (all a (type) (fun a a)))
            (typebind (tyvardecl DCert (type)) (all a (type) (fun a a)))
            (typebind
              (tyvardecl Interval (fun (type) (type)))
              (lam a (type) (all a (type) (fun a a)))
            )
            (typebind (tyvardecl TxInInfo (type)) (all a (type) (fun a a)))
            (typebind (tyvardecl TxOut (type)) (all a (type) (fun a a)))
            (typebind
              (tyvardecl StakingCredential (type)) (all a (type) (fun a a))
            )
            (typebind
              (tyvardecl Tuple2 (fun (type) (fun (type) (type))))
              (lam a (type) (lam a (type) (all a (type) (fun a a))))
            )
            (datatypebind
              (datatype
                (tyvardecl TxInfo (type))

                TxInfo_match
                (vardecl
                  TxInfo
                  (fun
                    [ List TxInInfo ]
                    (fun
                      [ List TxOut ]
                      (fun
                        [
                          [
                            (lam
                              k
                              (type)
                              (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                            )
                            (con bytestring)
                          ]
                          [
                            [
                              (lam
                                k
                                (type)
                                (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                              )
                              (con bytestring)
                            ]
                            (con integer)
                          ]
                        ]
                        (fun
                          [
                            [
                              (lam
                                k
                                (type)
                                (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                              )
                              (con bytestring)
                            ]
                            [
                              [
                                (lam
                                  k
                                  (type)
                                  (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                                )
                                (con bytestring)
                              ]
                              (con integer)
                            ]
                          ]
                          (fun
                            [ List DCert ]
                            (fun
                              [
                                List
                                [ [ Tuple2 StakingCredential ] (con integer) ]
                              ]
                              (fun
                                [ Interval (con integer) ]
                                (fun
                                  [ List (con bytestring) ]
                                  (fun
                                    [
                                      List
                                      [ [ Tuple2 (con bytestring) ] (con data) ]
                                    ]
                                    (fun (con bytestring) TxInfo)
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
            (datatypebind
              (datatype
                (tyvardecl ScriptContext (type))

                ScriptContext_match
                (vardecl
                  ScriptContext (fun TxInfo (fun ScriptPurpose ScriptContext))
                )
              )
            )
            (datatypebind
              (datatype
                (tyvardecl Bool (type))

                Bool_match
                (vardecl True Bool) (vardecl False Bool)
              )
            )
            (datatypebind
              (datatype
                (tyvardecl Maybe (fun (type) (type)))
                (tyvardecl a (type))
                Maybe_match
                (vardecl Just (fun a [ Maybe a ])) (vardecl Nothing [ Maybe a ])
              )
            )
            (lam
              w
              MultiSig
              (lam
                w
                Unit
                (lam
                  w
                  Unit
                  (lam
                    w
                    ScriptContext
                    [
                      { [ MultiSig_match w ] Bool }
                      (lam
                        ww
                        [ List (con bytestring) ]
                        (lam
                          ww
                          (con integer)
                          {
                            [
                              [
                                {
                                  [
                                    Bool_match
                                    [
                                      [
                                        [
                                          { (builtin ifThenElse) Bool }
                                          [
                                            [
                                              (builtin lessThanInteger)
                                              (let
                                                (nonrec)
                                                (termbind
                                                  (strict)
                                                  (vardecl
                                                    t [ List (con bytestring) ]
                                                  )
                                                  [
                                                    [
                                                      [
                                                        {
                                                          {
                                                            foldr
                                                            (con bytestring)
                                                          }
                                                          [
                                                            List
                                                            (con bytestring)
                                                          ]
                                                        }
                                                        (lam
                                                          e
                                                          (con bytestring)
                                                          (lam
                                                            xs
                                                            [
                                                              List
                                                              (con bytestring)
                                                            ]
                                                            [
                                                              {
                                                                [
                                                                  ScriptContext_match
                                                                  w
                                                                ]
                                                                [
                                                                  List
                                                                  (con
                                                                    bytestring
                                                                  )
                                                                ]
                                                              }
                                                              (lam
                                                                ds
                                                                TxInfo
                                                                (lam
                                                                  ds
                                                                  ScriptPurpose
                                                                  [
                                                                    {
                                                                      [
                                                                        TxInfo_match
                                                                        ds
                                                                      ]
                                                                      [
                                                                        List
                                                                        (con
                                                                          bytestring
                                                                        )
                                                                      ]
                                                                    }
                                                                    (lam
                                                                      ww
                                                                      [
                                                                        List
                                                                        TxInInfo
                                                                      ]
                                                                      (lam
                                                                        ww
                                                                        [
                                                                          List
                                                                          TxOut
                                                                        ]
                                                                        (lam
                                                                          ww
                                                                          [
                                                                            [
                                                                              (lam
                                                                                k
                                                                                (type)
                                                                                (lam
                                                                                  v
                                                                                  (type)
                                                                                  [
                                                                                    List
                                                                                    [
                                                                                      [
                                                                                        Tuple2
                                                                                        k
                                                                                      ]
                                                                                      v
                                                                                    ]
                                                                                  ]
                                                                                )
                                                                              )
                                                                              (con
                                                                                bytestring
                                                                              )
                                                                            ]
                                                                            [
                                                                              [
                                                                                (lam
                                                                                  k
                                                                                  (type)
                                                                                  (lam
                                                                                    v
                                                                                    (type)
                                                                                    [
                                                                                      List
                                                                                      [
                                                                                        [
                                                                                          Tuple2
                                                                                          k
                                                                                        ]
                                                                                        v
                                                                                      ]
                                                                                    ]
                                                                                  )
                                                                                )
                                                                                (con
                                                                                  bytestring
                                                                                )
                                                                              ]
                                                                              (con
                                                                                integer
                                                                              )
                                                                            ]
                                                                          ]
                                                                          (lam
                                                                            ww
                                                                            [
                                                                              [
                                                                                (lam
                                                                                  k
                                                                                  (type)
                                                                                  (lam
                                                                                    v
                                                                                    (type)
                                                                                    [
                                                                                      List
                                                                                      [
                                                                                        [
                                                                                          Tuple2
                                                                                          k
                                                                                        ]
                                                                                        v
                                                                                      ]
                                                                                    ]
                                                                                  )
                                                                                )
                                                                                (con
                                                                                  bytestring
                                                                                )
                                                                              ]
                                                                              [
                                                                                [
                                                                                  (lam
                                                                                    k
                                                                                    (type)
                                                                                    (lam
                                                                                      v
                                                                                      (type)
                                                                                      [
                                                                                        List
                                                                                        [
                                                                                          [
                                                                                            Tuple2
                                                                                            k
                                                                                          ]
                                                                                          v
                                                                                        ]
                                                                                      ]
                                                                                    )
                                                                                  )
                                                                                  (con
                                                                                    bytestring
                                                                                  )
                                                                                ]
                                                                                (con
                                                                                  integer
                                                                                )
                                                                              ]
                                                                            ]
                                                                            (lam
                                                                              ww
                                                                              [
                                                                                List
                                                                                DCert
                                                                              ]
                                                                              (lam
                                                                                ww
                                                                                [
                                                                                  List
                                                                                  [
                                                                                    [
                                                                                      Tuple2
                                                                                      StakingCredential
                                                                                    ]
                                                                                    (con
                                                                                      integer
                                                                                    )
                                                                                  ]
                                                                                ]
                                                                                (lam
                                                                                  ww
                                                                                  [
                                                                                    Interval
                                                                                    (con
                                                                                      integer
                                                                                    )
                                                                                  ]
                                                                                  (lam
                                                                                    ww
                                                                                    [
                                                                                      List
                                                                                      (con
                                                                                        bytestring
                                                                                      )
                                                                                    ]
                                                                                    (lam
                                                                                      ww
                                                                                      [
                                                                                        List
                                                                                        [
                                                                                          [
                                                                                            Tuple2
                                                                                            (con
                                                                                              bytestring
                                                                                            )
                                                                                          ]
                                                                                          (con
                                                                                            data
                                                                                          )
                                                                                        ]
                                                                                      ]
                                                                                      (lam
                                                                                        ww
                                                                                        (con
                                                                                          bytestring
                                                                                        )
                                                                                        {
                                                                                          [
                                                                                            [
                                                                                              {
                                                                                                [
                                                                                                  Bool_match
                                                                                                  {
                                                                                                    [
                                                                                                      [
                                                                                                        {
                                                                                                          [
                                                                                                            {
                                                                                                              Maybe_match
                                                                                                              (con
                                                                                                                bytestring
                                                                                                              )
                                                                                                            }
                                                                                                            [
                                                                                                              [
                                                                                                                [
                                                                                                                  {
                                                                                                                    {
                                                                                                                      fFoldableNil_cfoldMap
                                                                                                                      [
                                                                                                                        (lam
                                                                                                                          a
                                                                                                                          (type)
                                                                                                                          [
                                                                                                                            Maybe
                                                                                                                            a
                                                                                                                          ]
                                                                                                                        )
                                                                                                                        (con
                                                                                                                          bytestring
                                                                                                                        )
                                                                                                                      ]
                                                                                                                    }
                                                                                                                    (con
                                                                                                                      bytestring
                                                                                                                    )
                                                                                                                  }
                                                                                                                  [
                                                                                                                    [
                                                                                                                      {
                                                                                                                        CConsMonoid
                                                                                                                        [
                                                                                                                          (lam
                                                                                                                            a
                                                                                                                            (type)
                                                                                                                            [
                                                                                                                              Maybe
                                                                                                                              a
                                                                                                                            ]
                                                                                                                          )
                                                                                                                          (con
                                                                                                                            bytestring
                                                                                                                          )
                                                                                                                        ]
                                                                                                                      }
                                                                                                                      (lam
                                                                                                                        ds
                                                                                                                        [
                                                                                                                          (lam
                                                                                                                            a
                                                                                                                            (type)
                                                                                                                            [
                                                                                                                              Maybe
                                                                                                                              a
                                                                                                                            ]
                                                                                                                          )
                                                                                                                          (con
                                                                                                                            bytestring
                                                                                                                          )
                                                                                                                        ]
                                                                                                                        (lam
                                                                                                                          b
                                                                                                                          [
                                                                                                                            (lam
                                                                                                                              a
                                                                                                                              (type)
                                                                                                                              [
                                                                                                                                Maybe
                                                                                                                                a
                                                                                                                              ]
                                                                                                                            )
                                                                                                                            (con
                                                                                                                              bytestring
                                                                                                                            )
                                                                                                                          ]
                                                                                                                          {
                                                                                                                            [
                                                                                                                              [
                                                                                                                                {
                                                                                                                                  [
                                                                                                                                    {
                                                                                                                                      Maybe_match
                                                                                                                                      (con
                                                                                                                                        bytestring
                                                                                                                                      )
                                                                                                                                    }
                                                                                                                                    ds
                                                                                                                                  ]
                                                                                                                                  (all
                                                                                                                                    dead
                                                                                                                                    (type)
                                                                                                                                    [
                                                                                                                                      (lam
                                                                                                                                        a
                                                                                                                                        (type)
                                                                                                                                        [
                                                                                                                                          Maybe
                                                                                                                                          a
                                                                                                                                        ]
                                                                                                                                      )
                                                                                                                                      (con
                                                                                                                                        bytestring
                                                                                                                                      )
                                                                                                                                    ]
                                                                                                                                  )
                                                                                                                                }
                                                                                                                                (lam
                                                                                                                                  ipv
                                                                                                                                  (con
                                                                                                                                    bytestring
                                                                                                                                  )
                                                                                                                                  (abs
                                                                                                                                    dead
                                                                                                                                    (type)
                                                                                                                                    ds
                                                                                                                                  )
                                                                                                                                )
                                                                                                                              ]
                                                                                                                              (abs
                                                                                                                                dead
                                                                                                                                (type)
                                                                                                                                b
                                                                                                                              )
                                                                                                                            ]
                                                                                                                            (all
                                                                                                                              dead
                                                                                                                              (type)
                                                                                                                              dead
                                                                                                                            )
                                                                                                                          }
                                                                                                                        )
                                                                                                                      )
                                                                                                                    ]
                                                                                                                    {
                                                                                                                      Nothing
                                                                                                                      (con
                                                                                                                        bytestring
                                                                                                                      )
                                                                                                                    }
                                                                                                                  ]
                                                                                                                ]
                                                                                                                (lam
                                                                                                                  x
                                                                                                                  (con
                                                                                                                    bytestring
                                                                                                                  )
                                                                                                                  {
                                                                                                                    [
                                                                                                                      [
                                                                                                                        {
                                                                                                                          [
                                                                                                                            Bool_match
                                                                                                                            [
                                                                                                                              [
                                                                                                                                [
                                                                                                                                  {
                                                                                                                                    (builtin
                                                                                                                                      ifThenElse
                                                                                                                                    )
                                                                                                                                    Bool
                                                                                                                                  }
                                                                                                                                  [
                                                                                                                                    [
                                                                                                                                      (builtin
                                                                                                                                        equalsByteString
                                                                                                                                      )
                                                                                                                                      e
                                                                                                                                    ]
                                                                                                                                    x
                                                                                                                                  ]
                                                                                                                                ]
                                                                                                                                True
                                                                                                                              ]
                                                                                                                              False
                                                                                                                            ]
                                                                                                                          ]
                                                                                                                          (all
                                                                                                                            dead
                                                                                                                            (type)
                                                                                                                            [
                                                                                                                              Maybe
                                                                                                                              (con
                                                                                                                                bytestring
                                                                                                                              )
                                                                                                                            ]
                                                                                                                          )
                                                                                                                        }
                                                                                                                        (abs
                                                                                                                          dead
                                                                                                                          (type)
                                                                                                                          [
                                                                                                                            {
                                                                                                                              Just
                                                                                                                              (con
                                                                                                                                bytestring
                                                                                                                              )
                                                                                                                            }
                                                                                                                            x
                                                                                                                          ]
                                                                                                                        )
                                                                                                                      ]
                                                                                                                      (abs
                                                                                                                        dead
                                                                                                                        (type)
                                                                                                                        {
                                                                                                                          Nothing
                                                                                                                          (con
                                                                                                                            bytestring
                                                                                                                          )
                                                                                                                        }
                                                                                                                      )
                                                                                                                    ]
                                                                                                                    (all
                                                                                                                      dead
                                                                                                                      (type)
                                                                                                                      dead
                                                                                                                    )
                                                                                                                  }
                                                                                                                )
                                                                                                              ]
                                                                                                              ww
                                                                                                            ]
                                                                                                          ]
                                                                                                          (all
                                                                                                            dead
                                                                                                            (type)
                                                                                                            Bool
                                                                                                          )
                                                                                                        }
                                                                                                        (lam
                                                                                                          ds
                                                                                                          (con
                                                                                                            bytestring
                                                                                                          )
                                                                                                          (abs
                                                                                                            dead
                                                                                                            (type)
                                                                                                            True
                                                                                                          )
                                                                                                        )
                                                                                                      ]
                                                                                                      (abs
                                                                                                        dead
                                                                                                        (type)
                                                                                                        False
                                                                                                      )
                                                                                                    ]
                                                                                                    (all
                                                                                                      dead
                                                                                                      (type)
                                                                                                      dead
                                                                                                    )
                                                                                                  }
                                                                                                ]
                                                                                                (all
                                                                                                  dead
                                                                                                  (type)
                                                                                                  [
                                                                                                    List
                                                                                                    (con
                                                                                                      bytestring
                                                                                                    )
                                                                                                  ]
                                                                                                )
                                                                                              }
                                                                                              (abs
                                                                                                dead
                                                                                                (type)
                                                                                                [
                                                                                                  [
                                                                                                    {
                                                                                                      Cons
                                                                                                      (con
                                                                                                        bytestring
                                                                                                      )
                                                                                                    }
                                                                                                    e
                                                                                                  ]
                                                                                                  xs
                                                                                                ]
                                                                                              )
                                                                                            ]
                                                                                            (abs
                                                                                              dead
                                                                                              (type)
                                                                                              xs
                                                                                            )
                                                                                          ]
                                                                                          (all
                                                                                            dead
                                                                                            (type)
                                                                                            dead
                                                                                          )
                                                                                        }
                                                                                      )
                                                                                    )
                                                                                  )
                                                                                )
                                                                              )
                                                                            )
                                                                          )
                                                                        )
                                                                      )
                                                                    )
                                                                  ]
                                                                )
                                                              )
                                                            ]
                                                          )
                                                        )
                                                      ]
                                                      { Nil (con bytestring) }
                                                    ]
                                                    ww
                                                  ]
                                                )
                                                [
                                                  [
                                                    [
                                                      [
                                                        {
                                                          {
                                                            fFoldableNil_cfoldMap
                                                            [
                                                              (lam a (type) a)
                                                              [
                                                                (lam
                                                                  a
                                                                  (type)
                                                                  (fun a a)
                                                                )
                                                                (con integer)
                                                              ]
                                                            ]
                                                          }
                                                          (con bytestring)
                                                        }
                                                        [
                                                          {
                                                            (abs
                                                              a
                                                              (type)
                                                              (lam
                                                                v
                                                                [ Monoid a ]
                                                                [
                                                                  [
                                                                    {
                                                                      CConsMonoid
                                                                      [
                                                                        (lam
                                                                          a
                                                                          (type)
                                                                          a
                                                                        )
                                                                        a
                                                                      ]
                                                                    }
                                                                    (lam
                                                                      eta
                                                                      [
                                                                        (lam
                                                                          a
                                                                          (type)
                                                                          a
                                                                        )
                                                                        a
                                                                      ]
                                                                      (lam
                                                                        eta
                                                                        [
                                                                          (lam
                                                                            a
                                                                            (type)
                                                                            a
                                                                          )
                                                                          a
                                                                        ]
                                                                        [
                                                                          [
                                                                            [
                                                                              {
                                                                                p1Monoid
                                                                                a
                                                                              }
                                                                              v
                                                                            ]
                                                                            eta
                                                                          ]
                                                                          eta
                                                                        ]
                                                                      )
                                                                    )
                                                                  ]
                                                                  [
                                                                    { mempty a }
                                                                    v
                                                                  ]
                                                                ]
                                                              )
                                                            )
                                                            [
                                                              (lam
                                                                a
                                                                (type)
                                                                (fun a a)
                                                              )
                                                              (con integer)
                                                            ]
                                                          }
                                                          [
                                                            [
                                                              {
                                                                CConsMonoid
                                                                [
                                                                  (lam
                                                                    a
                                                                    (type)
                                                                    (fun a a)
                                                                  )
                                                                  (con integer)
                                                                ]
                                                              }
                                                              (lam
                                                                ds
                                                                [
                                                                  (lam
                                                                    a
                                                                    (type)
                                                                    (fun a a)
                                                                  )
                                                                  (con integer)
                                                                ]
                                                                (lam
                                                                  ds
                                                                  [
                                                                    (lam
                                                                      a
                                                                      (type)
                                                                      (fun a a)
                                                                    )
                                                                    (con
                                                                      integer
                                                                    )
                                                                  ]
                                                                  (lam
                                                                    x
                                                                    (con
                                                                      integer
                                                                    )
                                                                    [
                                                                      ds
                                                                      [ ds x ]
                                                                    ]
                                                                  )
                                                                )
                                                              )
                                                            ]
                                                            (lam
                                                              x (con integer) x
                                                            )
                                                          ]
                                                        ]
                                                      ]
                                                      (lam
                                                        x
                                                        (con bytestring)
                                                        (lam
                                                          y
                                                          (con integer)
                                                          [
                                                            [
                                                              (builtin
                                                                addInteger
                                                              )
                                                              y
                                                            ]
                                                            (con integer 1)
                                                          ]
                                                        )
                                                      )
                                                    ]
                                                    t
                                                  ]
                                                  (con integer 0)
                                                ]
                                              )
                                            ]
                                            ww
                                          ]
                                        ]
                                        False
                                      ]
                                      True
                                    ]
                                  ]
                                  (all dead (type) Bool)
                                }
                                (abs dead (type) True)
                              ]
                              (abs
                                dead
                                (type)
                                [
                                  [
                                    { (builtin trace) Bool }
                                    (con string "not enough signatures")
                                  ]
                                  False
                                ]
                              )
                            ]
                            (all dead (type) dead)
                          }
                        )
                      )
                    ]
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)