## REST-Client script
# If you don't know how to use this script, see:  https://github.com/pashky/restclient.el for instruction

#
# should echo
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{"jsonrpc": "2.0", "method": "echo", "params": "hello world", "id": 0}
#
# should fail. `add` method is unknown
POST http://localhost:3000/json-rpc
Content-Type: application/json
{"jsonrpc": "2.0", "method": "add", "params": [1,1], "id": 0}
#
# should print message on the console
# TODO should we modify this to print the target addresses?
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{"jsonrpc": "2.0", "method": "print", "params": "print me", "id": 0}
#
# lookup fot txoutrefs
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxoTxOutReport"
, "params": "addr1q837de0y7j3ncegph2a8mc0e86q9evwtekd3ejhlpr97wclrumj7fa9r83jsrw460hslj05qtjcuhnvmrn907zxtua3skv7yyl"
, "id": 9
}
#
# fetch 100 rows from sqlite
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxoTxOutReports"
, "params": 100
, "id": 14
}
#
# fetch plutus converted addresses the user had provided
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "addressesBech32Report"
, "params": 100
, "id": 11
}
#
#
# get the top 100 utxos, sorted by ledger.Address
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxosReport"
, "params": 100
, "id": 14
}
#
# REST call. get the current time.  This may be used as health-check
GET http://localhost:3000/rest/time
#
# REST call, get the user provided addresses
GET http://localhost:3000/rest/addresses
# REST call, get the user provided addresses
