## REST-Client script
# If you don't know how to use this script, see: https://github.com/pashky/restclient.el for instruction

#
#
# should generate error, Unknown method
POST http://localhost:3000/json-rpc
Content-Type: application/json
{"jsonrpc": "2.0", "method": "add", "params": [1,1], "id": 0}
#
# should print addresses to index on the console as JSON array
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{"jsonrpc": "2.0", "method": "print", "params": "this param is ignored", "id": 0}
# should echo
POST http://localhost:3000/json-rpc
Content-Type: application/json-rpc
{
"jsonrpc": "2.0", "method": "echo", "params": "hello world", "id": 0}
#
# lookup, should return JSON-RPC error with cause of the error:
# generated error: Bech32DecodingError (StringToDecodeContainsInvalidChars [])
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxoJsonReport"
, "params": "xxx_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0"
, "id": 2
}
#
# lookup, should return result with datum not null
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxoJsonReport"
, "params": "addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0"
, "id": 92
}
#
# lookup, should return results with scriptData not null
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "utxoJsonReport"
, "params": "addr_test1wrpn0ad8rj3pgfpzae5tghpf325nyvh94zfkj3kzgvxzvcc2zuac6"
, "id":21
}
#
# addresses with non null scriptDataum from preview network
#
# addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk
# addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
# addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0
#
# addresses with datum non null from preview network
#
#addr_test1wqnp362vmvr8jtc946d3a3utqgclfdl5y9d3kn849e359hst7hkqk
#addr_test1wqr4uz0tp75fu8wrg6gm83t20aphuc9vt6n8kvu09ctkugq6ch8kj
#addr_test1wz3937ykmlcaqxkf4z7stxpsfwfn4re7ncy48yu8vutcpxgnj28k0

#
# fetch plutus converted addresses the user had provided
# This version of marconi-mamba simply ignores `100` and returns all rows from database. This is a todo item for next release
POST http://localhost:3000/json-rpc
Content-Type: application/json
{
"jsonrpc": "2.0"
, "method": "addressesBech32Report"
, "params": 100
, "id": 11
}
#
#
####  REST calls ####
#
# REST call, get the current time.  This may be used as health-check
GET http://localhost:3000/rest/time
#
# REST call, get the user-provided addresses
GET http://localhost:3000/rest/addresses
