-- File auto generated by purescript-bridge! --
module ServerTypes where

import Data.Eq (class Eq1)
import Data.Generic.Rep (class Generic)
import Data.Lens (Iso', Lens', Prism', lens, prism')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Lens.Record (prop)
import Data.Maybe (Maybe(..))
import Data.Newtype (class Newtype)
import Data.Show.Generic (genericShow)
import Data.Symbol (SProxy(SProxy))
import Prim (String)

import Prelude

newtype Hello
  = Hello
      { message :: String
      }


derive instance eqHello :: Eq Hello
derive instance ordHello :: Ord Hello
instance showHello :: Show Hello where
  show x = genericShow x
derive instance genericHello :: Generic Hello _
derive instance newtypeHello :: Newtype Hello _
--------------------------------------------------------------------------------
_Hello :: Iso' Hello { message :: String }
_Hello = _Newtype
--------------------------------------------------------------------------------
newtype TestHeader
  = TestHeader String


derive instance genericTestHeader :: Generic TestHeader _
derive instance newtypeTestHeader :: Newtype TestHeader _
--------------------------------------------------------------------------------
_TestHeader :: Iso' TestHeader String
_TestHeader = _Newtype
--------------------------------------------------------------------------------
