-- File auto generated by purescript-bridge! --
module Counter.ServerTypes where

import Prim (Int, String)

import Data.Generic (class Generic)


data AuthToken =
    VerySecret String

derive instance genericAuthToken :: Generic AuthToken

data CounterAction =
    CounterAdd Int
  | CounterSet Int

derive instance genericCounterAction :: Generic CounterAction

