#!/usr/bin/env bash
set -eEuo pipefail

error () {
    echo "$*" >&2
    exit 1
}

readonly ops_repo="input-output-hk/plutus-ops"
readonly ops_branch="master"
readonly name="plutus"
readonly rev="${GITHUB_SHA:-}"

if [ -z "${rev}" ]
then
    error "GITHUB_SHA environment variable not set!"
fi

ref="${GITHUB_REF_SLUG:-}"
ref="${ref/v[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/vYYYY-MM-DD}"
declare -r ref

if [ -z "${ref}" ]
then
    error "GITHUB_REF_SLUG environment variable not set!"
fi

declare -A ref_env_mapping=(
    [vYYYY-MM-DD]=plutusProduction
    [main]=plutusStaging
)

if [ ! -v 'ref_env_mapping[${ref}]' ]
then
    error "Ref ${ref} does not correspond to any known env"
fi
env="${ref_env_mapping[${ref}]}"

if [ "$#" -ne 0 ]
then
    error "USAGE: $0"
fi

### Set up scratch space

tmp=/var/lib/empty

cleanup () {
    if [ "${tmp}" != "/var/lib/empty" ]
    then
        rm -fR "${tmp}"
    fi
}
trap cleanup EXIT

tmp="$(mktemp -d)"

declare -r tmp

### Write the new revision cue file

cat > "${tmp}/${name}.cue" <<EOF
package ${env}

${name}: "${rev}"
EOF



### Get the old revision cue file, exit if it's unchanged
hub api -XGET -F ref="${ops_branch}" "/repos/${ops_repo}/contents/revisions/${env}/${name}.cue" > "${tmp}/${name}.cue-contents.json"
prev_hash="$(jq --join-output '.sha' < "${tmp}/${name}.cue-contents.json")"
jq --join-output '.content' < "${tmp}/${name}.cue-contents.json" | base64 -d > "${tmp}/${name}-old.cue"
if diff -q "${tmp}/${name}.cue" "${tmp}/${name}-old.cue" >/dev/null
then
    exit 0
fi

### Commit the new revision cue file
base64 "${tmp}/${name}.cue" > "${tmp}/${name}.cue-encoded"
echo "${env}: Bump ${name} to ${rev}" > "${tmp}/commit-message"
hub api -XPUT \
    -F message=@"${tmp}/commit-message" \
    -F content=@"${tmp}/${name}.cue-encoded" \
    -F sha="${prev_hash}" \
    -F branch="${ops_branch}" \
    "/repos/${ops_repo}/contents/revisions/${env}/${name}.cue"
