name: "Build and Deploy to Github Pages"
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-haddock-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Build haddock site
        run: |
          nix build .#read-the-docs-site --out-link result
          mkdir dist
          cp -RL ./result/haddock/* ./dist/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}
