name: Plutus Playground E2E Tests

on:
  schedule:
  - cron: '0 4 * * *'
  push:
    branches: [ playwright-e2e-tests ]
  workflow_dispatch:

jobs:
  plutus-playground-e2e-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Plutus
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.2.0.0'

    - name: Setup Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Build Plutus Playground
      run: nix-build -A plutus-playground.client -A plutus-playground.server
        #  nix build -f default.nix plutus.haskell.packages.plutus-core.components.library

    - name: Run Plutus Playground
      working-directory: ./plutus-playground-client
      env:
        CLIENT_PORT: 8009
      run: |
        nix-shell --run 'plutus-playground-server' ../shell.nix &
        nix-shell --run 'npm start' ../shell.nix &
        while ! echo exit | nc localhost $CLIENT_PORT; do echo "Waiting for playground client on $CLIENT_PORT" && sleep 10; done
  
    - name: Setup NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: '12.12.0'
  
    - name: Setup Playwright
      working-directory: ./e2e-tests/
      run: |
        npm install -D @playwright/test
#        npx playwright install-deps
        npx playwright install
  
    - name: Run Tests
      working-directory: ./e2e-tests/
      run: |
        npx playwright test
  
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: e2e-tests/html-report/index.html
        retention-days: 5